image: node:14

test: &test 
  caches:
    - node
  script:
    - yarn install
    - node_modules/eslint/bin/eslint.js src --ext .js,.jsx,.ts,.tsx
    - cd server
    - yarn install
    - node_modules/eslint/bin/eslint.js src --ext .js,.jsx,.ts,.tsx

validate_build: &validate_build
  caches:
    - node
  script:
    - node_modules/.bin/react-scripts build

pipelines:
  default:
    - step:
        <<: *test
    - step:
        <<: *validate_build

  branches:
    master:
      - step:
          <<: *test 
      - step:
          <<: *validate_build

      - step:
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master
