version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - server-node-modules-{{ checksum "server/yarn.lock" }}
            # if cache for exact version is not present then load any most recent one
            - server-node-modules-
      - restore_cache:
          keys:
            - client-node-modules-{{ checksum "client/yarn.lock" }}
            - client-node-modules-
      - node/with-cache:
          steps:
            - run: cd client && yarn install
            - run: cd client && node_modules/eslint/bin/eslint.js src --ext .js,.jsx,.ts,.tsx
            - run: cd client && yarn test
            - run: cd server && yarn install
            - run: cd server && node_modules/eslint/bin/eslint.js src --ext .js,.jsx,.ts,.tsx
            # - run: cd server && ./node_modules/.bin/jest
      - save_cache:
          key: client-node-modules-{{ checksum "client/yarn.lock" }}
          paths:
            - client/node_modules
      - save_cache:
          key: server-node-modules-{{ checksum "server/yarn.lock" }}
          paths:
            - server/node_modules
workflows:
    build-and-test:
      jobs:
        - build-and-test